### PR TITLE
Use more faker providers

### PR DESCRIPTION
**Pull request by olegstepura**
- Use more faker providers
- Stop using builtin magento2 config. Leave it only as an example. One of the reasons is that github.com/mpchadwick/dbanon/bindata no longer exists.

### CODE REVIEW

**Comment by mpchadwick** [comment]
I'm OK with the additional raw providers, don't understand the other changes and want to keep the Magento 2 config bundled into the binary

**Comment by mpchadwick** [comment]
By the way, for bindata I found that there's an issue with the `Makefile` build on Go 1.18, which might have been what you were experiencing. It should build with Go 1.18 with this change

https://github.com/mpchadwick/dbanon/commit/2fa0efd53a3fdba4230022b1f99b6c788d5d1aa8#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R7

**Comment by olegstepura** [comment]
Why do you need magento built-in? 
This tool goes very well beyond magento. It's much more then just a tool for magento 😉 We are using it on a custom Symfony Project and it works great with some extra fixes.

My suggestion was to keep magento configs, but only as an example files in the repo. This is especially nice because user can fix it the way he needs.

**Comment by mpchadwick** [comment]
@olegstepura - I'm glad to hear you're using it on your project. Having the Magento config bundled is a convenience for anyone using the tool with Magento. If there were other standard configs for other popular frameworks I'd accept PRs to bundle those as well. The intention is that the tool can be used for any custom database, but also want to make things easy for standard platforms as well.

**Pull request closed without merging**
